#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : simplescreenrecorder
Version  : 0.3.11
Release  : 1
URL      : https://github.com/MaartenBaert/ssr/archive/0.3.11.tar.gz
Source0  : https://github.com/MaartenBaert/ssr/archive/0.3.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: simplescreenrecorder-bin = %{version}-%{release}
Requires: simplescreenrecorder-data = %{version}-%{release}
Requires: simplescreenrecorder-license = %{version}-%{release}
Requires: simplescreenrecorder-man = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : extra-cmake-modules pkgconfig(libpulse)
BuildRequires : glibc-dev
BuildRequires : glu-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(libavcodec)
BuildRequires : pkgconfig(libavformat)
BuildRequires : pkgconfig(libavutil)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libswscale)
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtx11extras-dev

%description
SimpleScreenRecorder
====================
SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC :).

%package bin
Summary: bin components for the simplescreenrecorder package.
Group: Binaries
Requires: simplescreenrecorder-data = %{version}-%{release}
Requires: simplescreenrecorder-license = %{version}-%{release}

%description bin
bin components for the simplescreenrecorder package.


%package data
Summary: data components for the simplescreenrecorder package.
Group: Data

%description data
data components for the simplescreenrecorder package.


%package dev
Summary: dev components for the simplescreenrecorder package.
Group: Development
Requires: simplescreenrecorder-bin = %{version}-%{release}
Requires: simplescreenrecorder-data = %{version}-%{release}
Provides: simplescreenrecorder-devel = %{version}-%{release}
Requires: simplescreenrecorder = %{version}-%{release}

%description dev
dev components for the simplescreenrecorder package.


%package license
Summary: license components for the simplescreenrecorder package.
Group: Default

%description license
license components for the simplescreenrecorder package.


%package man
Summary: man components for the simplescreenrecorder package.
Group: Default

%description man
man components for the simplescreenrecorder package.


%prep
%setup -q -n ssr-0.3.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566941514
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DWITH_QT5=TRUE
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1566941514
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/simplescreenrecorder
cp COPYING %{buildroot}/usr/share/package-licenses/simplescreenrecorder/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/simplescreenrecorder
/usr/bin/ssr-glinject

%files data
%defattr(-,root,root,-)
/usr/share/appdata/simplescreenrecorder.appdata.xml
/usr/share/applications/simplescreenrecorder.desktop
/usr/share/icons/hicolor/128x128/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/128x128/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/128x128/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/128x128/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/128x128/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/192x192/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/192x192/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/192x192/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/192x192/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/192x192/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/22x22/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/22x22/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/22x22/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/22x22/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/22x22/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/24x24/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/24x24/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/24x24/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/24x24/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/24x24/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/32x32/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/32x32/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/32x32/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/32x32/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/32x32/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/48x48/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/48x48/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/48x48/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/48x48/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/48x48/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/64x64/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/64x64/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/64x64/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/64x64/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/64x64/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/96x96/apps/simplescreenrecorder-error.png
/usr/share/icons/hicolor/96x96/apps/simplescreenrecorder-idle.png
/usr/share/icons/hicolor/96x96/apps/simplescreenrecorder-paused.png
/usr/share/icons/hicolor/96x96/apps/simplescreenrecorder-recording.png
/usr/share/icons/hicolor/96x96/apps/simplescreenrecorder.png
/usr/share/icons/hicolor/scalable/apps/simplescreenrecorder-error.svg
/usr/share/icons/hicolor/scalable/apps/simplescreenrecorder-idle.svg
/usr/share/icons/hicolor/scalable/apps/simplescreenrecorder-paused.svg
/usr/share/icons/hicolor/scalable/apps/simplescreenrecorder-recording.svg
/usr/share/icons/hicolor/scalable/apps/simplescreenrecorder.svg
/usr/share/simplescreenrecorder/output-profiles/High%20Quality%20Intermediate.conf
/usr/share/simplescreenrecorder/output-profiles/Live%20Stream%20%281000kbps%29.conf
/usr/share/simplescreenrecorder/output-profiles/Live%20Stream%20%282000kbps%29.conf
/usr/share/simplescreenrecorder/output-profiles/Live%20Stream%20%283000kbps%29.conf
/usr/share/simplescreenrecorder/output-profiles/YouTube.conf

%files dev
%defattr(-,root,root,-)
/usr/lib64/libssr-glinject.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/simplescreenrecorder/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/simplescreenrecorder.1
/usr/share/man/man1/ssr-glinject.1
